hr_perday = 1
ut_config = dict(
    issues=dict( 
        driver='gitlab',
        addr='https://gitlab.com/',
        token='XX=',
        prj_id='18454432',
        
        addr2='http://gitibm.wnc.com.tw/',        
        token2='XX=',
        prj_id2='2',
        token3='mYqiBEM9iReVxmbPeSXh',
        prj_dir='C:/PROJ_DIR/1_PM/1.0_Backlog/',
        keycode='SD',
        tgt_file='WNC-SD.xlsx',
        row_per_page=100,
        map_columns={
            'Category': '$SQLG',
            'Story': 'title',
            'Solution/Confirmation': 'description',
            'Status': 'state',
            'Stakeholder': 'author.username',
            'Owner': 'assignee.username',
            'Request DT': 'created_at',
            'PlanIn DT': 'due_date',
            'Planned DT': 'due_date',
            'Completed DT': 'closed_at',
            'Comment': 'label_str',
            'GTD': None,
            'Remain HR': 'time_stats.total_time_spent',
            'Ideal HR': 'time_stats.time_estimate',
            'Story Point': '$1',
            'Priority': 'Priority',
            'LogType': 'log_type',
            'ReqTeam': None,
            'ownModule': None,
            'logKey': 'iid',
            'reportID': None,
            'isRTC': None,
            'rptName': None,
            'defaultTeam': None,
            'Remark': '$N/A',
        },
        map_name={
            'Shongweb614': 'Shiang Chen',
            'soniayml': 'Sonia Yang',
            'jessewei': 'Jesse Wei',         
            'little880536': 'Bucky Lee',
            'EuniceYC': 'Eunice',           
            'SunnyWangg': 'Sunny Wang',               
            'Cathy_CH_Lin': 'Cathy Lin',               
            'gracechien2': 'Grace Chien',               
            'Jerry-ky-chen': 'Jerry Chen',                           
            'Silviaaaa': 'Silvia Yang', 
            'joechen0713': 'Joe Chen', 
            '-': 'Jesse',
        },
        map_state={
            'closed': 'Completed',
            'opened': 'Process',
            '-': 'Process',
        },
        map_priority=dict(
        ),

        map_log_type=dict(
        ),
        drivers={        
            'gsheet': dict(
                # addr='ProjectControlBook',
                addr='https://docs.google.com/spreadsheets/d/1FhgUqM44_SGYJ_M53aojuzOyQ9tT6V7hH1dX0dNWikw/edit?usp=sharing',
                token='service_secret.json',
                prj_id='IV_DG',
                prj_dir1='/app/backlog/',
                prj_dir2='C:/Users/JESSEWEI/Box/Invnetec-CEO_Dashboard_Phase2/backlog/',            
                prj_dir='C:/Users/JESSEWEI/Box/Invnetec-CEO_Dashboard_Phase2/01_PM/0101_Backlog/',  
                # src_file = '/workspaces/sqlglib/sqlglib/proj_dir/01_PM/0102_BacklogSummary/ProjectControlBook_v1.0.xlsx',
                tgt_file='IV-PCB.xlsx',
                close_deadline = '20210801',
                row_per_page=100,
                col_map_rules = [{
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'Task',
                    'Solution/Confirmation': None,
                    'Status': 'BA_Status',
                    'Stakeholder': 'Owner',
                    'Owner': 'BA_Owner',
                    'Request DT': 'BA_StartDate',
                    'PlanIn DT': 'BA_StartDate',
                    'Planned DT': 'BA_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-BA',
                    'ReqTeam': '$PM',
                    'ownModule': None,
                    'logKey': None,
                    'GlogKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PM',
                    'Remark': '$N/A',
                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'Task',
                    'Solution/Confirmation': None,
                    'Status': 'DG_Status',
                    'Stakeholder': 'BA_Owner',
                    'Owner': 'DG_Owner',
                    'Request DT': 'DG_StartDate',
                    'PlanIn DT': 'DG_StartDate',
                    'Planned DT': 'DG_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': f'${hr_perday}',
                    'LogType': '$系統-開發-DG',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',

                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'Task',
                    'Solution/Confirmation': None,
                    'Status': 'DM_Status',
                    'Stakeholder': 'DG_Owner',
                    'Owner': 'DM_Owner',
                    'Request DT': 'DM_StartDate',
                    'PlanIn DT': 'DM_StartDate',
                    'Planned DT': 'DM_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-DM',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',

                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'Task',
                    'Solution/Confirmation': None,
                    'Status': 'ETL_Status',
                    'Stakeholder': 'DM_Owner',
                    'Owner': 'ETL_Owner',
                    'Request DT': 'ETL_StartDate',
                    'PlanIn DT': 'ETL_StartDate',
                    'Planned DT': 'ETL_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-ETL',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'Task',
                    'Solution/Confirmation': None,
                    'Status': 'RPT_Status',
                    'Stakeholder': 'ETL_Owner',
                    'Owner': 'RPT_Owner',
                    'Request DT': 'RPT_StartDate',
                    'PlanIn DT': 'RPT_StartDate',
                    'Planned DT': 'RPT_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-RPT',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'Task',
                    'Solution/Confirmation': None,
                    'Status': 'FuncTest_Status',
                    'Stakeholder': 'RPT_Owner',
                    'Owner': 'FuncTest_Owner',
                    'Request DT': 'FuncTest_StartDate',
                    'PlanIn DT': 'FuncTest_StartDate',
                    'Planned DT': 'FuncTest_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-FT',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                }],
                stage_names = [
                    {'short_name': 'BA', 'long_name': 'BA'},
                    {'short_name': 'DG', 'long_name': 'DG'},
                    {'short_name': 'DM', 'long_name': 'DM'},
                    {'short_name': 'ETL', 'long_name': 'ETL'},
                    {'short_name': 'RPT', 'long_name': 'RPT'},
                    {'short_name': 'FT', 'long_name': 'FuncTest'},
                    # 'DG', 'TC', 'DM', 'FT', 'WT'
                ],
                map_name={
                    'Alex YH Chen': 'Alex',
                    'Anna Yang': 'Anna',
                    'Brian Hung': 'Brian',
                    'Cindy Cheng': 'Cindy',
                    'Cynthia Lin': 'CynthiaLin',
                    'Dennis Huang': 'Dennis',
                    'Effie Lin': 'Effie',
                    'Ellen Sun': 'EllenSun',
                    'Jane Liu': 'Jane',
                    'Johnny Kao': 'Johnny',
                    'Redmine Admin': 'Redmine',
                    'Sean Chiu': 'Sean',
                    'Stella Tseng': 'Stella',
                    'Sunny Chnag': 'Sunny',
                    'Joseph Wong': 'Joseph',
                    'ho2002': 'Aiden',
                    'benjaminchenibm': 'Benjamin',
                    'Irene.Tsai': 'Irene',
                    'ickw76': 'Issac',
                    'scliang123': 'Janus',
                    'rickyho': 'Ricky',
                    'soniayml': 'Sonia',
                    'flyingsophiee': 'Sophie',
                    'CassieLee': 'Cassie',
                    'linwj130013': 'Ivy',
                    'dcnlin': 'Deacon',
                    'marrinakong': 'Marrina',
                    'kuantsung.chen': 'KT',
                    'Jesse Wei': 'Jesse',
                    'gracechien2': 'Grace',
                    'Johnson Feng': 'JohnsonFeng',
                    'Felix Kuan': 'Felix',
                    'Jamie lin': 'Jamie',
                    'Ricky Ho': 'Ricky',
                    'Valen Chang': 'Valen',
                    'Viola Lin': 'Viola',
                    'Viola2 Lin': 'Viola',
                    '-': 'PMO',
                },
                map_state={
                    'Assigned': 'Process',
                    # 'Completed': 'Completed',
                    'Not started': 'Process',
                    'Open': 'Process',
                    'Opened': 'Process',
                    # 'Process': 'Process',
                    'Rejected': 'Cancelled',
                    'Rejected Closed': 'Cancelled',
                    'Resolved': 'Completed',
                    'Submitted': 'Process',
                    'Verify Closed': 'Completed',
                },
                map_priority={
                    'Critical': '5',
                    'High': '4',
                    'Medium': '3',
                    'Low': '2',
                },
                category_map = {
                    'PRODUCT': 'PROD',
                },
                map_log_type=dict(
                ),
                module_map = {
                    'PRODUCT': 'PROD',
                    'PROPOSAL': 'REQ',
                    'CAMPAIGN': 'PROJ',
                    'REPORT': 'MEM',
                    'LIBRARY': 'LIB',
                    'WORKFLOW': 'ADM',
                    'COMMON': 'ADM',
                    '': 'ADM',
                },
                
            ),
            'excel':dict(
                addr='https://docs.google.com/spreadsheets/d/1FhgUqM44_SGYJ_M53aojuzOyQ9tT6V7hH1dX0dNWikw/edit?usp=sharing',
                token='service_secret.json',
                prj_id='IEC_DG',
                prj_dir='C:/PROJ_DIR1/',  
                log_dir='01_PM/0101_Backlog/',  
                # src_file = '/workspaces/sqlglib/sqlglib/proj_dir/01_PM/0102_BacklogSummary/ProjectControlBook_v1.0.xlsx',          
                src_file = '01_PM/0102_BacklogSummary/ProjectControlBook_v2.0.xlsx', 
                #tgt_file='IEC-PCB.xlsx',
                tgt_file='IEC-PCB.xlsx',
                close_deadline = '20211201',
                row_per_page=100,
                col_map_rules = [{
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'BA_Status',
                    'Stakeholder': 'Owner',
                    'Owner': 'BA_Owner',
                    'Request DT': 'BA_StartDate',
                    'PlanIn DT': 'BA_StartDate',
                    'Planned DT': 'BA_EndDate',
                    'Completed DT': None,
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-BA',
                    'ReqTeam': '$PM',
                    'ownModule': None,
                    'logKey': None,
                    'GlogKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PM',
                    'Remark': '$N/A',
                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'DG_Status',
                    'Stakeholder': 'BA_Owner',
                    'Owner': 'DG_Owner',
                    'Request DT': 'DG_StartDate',
                    'PlanIn DT': 'DG_StartDate',
                    'Planned DT': 'DG_EndDate',
                    'Completed DT': None,
                    'Comment': 'Label',
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': f'${hr_perday}',
                    'LogType': '$系統-開發-DG',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',

                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'DM_Status',
                    'Stakeholder': 'DG_Owner',
                    'Owner': 'DM_Owner',
                    'Request DT': 'DM_StartDate',
                    'PlanIn DT': 'DM_StartDate',
                    'Planned DT': 'DM_EndDate',
                    'Completed DT': None,
                    'Comment': 'Label',
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-DM',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',

                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'ETL_Status',
                    'Stakeholder': 'DM_Owner',
                    'Owner': 'ETL_Owner',
                    'Request DT': 'ETL_StartDate',
                    'PlanIn DT': 'ETL_StartDate',
                    'Planned DT': 'ETL_EndDate',
                    'Completed DT': None,
                    'Comment': 'Label',
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-ETL',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'RPT_Status',
                    'Stakeholder': 'ETL_Owner',
                    'Owner': 'RPT_Owner',
                    'Request DT': 'RPT_StartDate',
                    'PlanIn DT': 'RPT_StartDate',
                    'Planned DT': 'RPT_EndDate',
                    'Completed DT': None,
                    'Comment': 'Label',
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-RPT',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                }, {
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'FuncTest_Status',
                    'Stakeholder': 'RPT_Owner',
                    'Owner': 'FuncTest_Owner',
                    'Request DT': 'FuncTest_StartDate',
                    'PlanIn DT': 'FuncTest_StartDate',
                    'Planned DT': 'FuncTest_EndDate',
                    'Completed DT': None,
                    'Comment': 'Label',
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-FT',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                },{
                    'PBI': 'Seq',
                    'Category': '$PCB',
                    'Story': 'ProductName',
                    'Solution/Confirmation': 'Task',
                    'Status': 'DGCheck_Status',
                    'Stakeholder': 'FuncTest_Owner',
                    'Owner': 'DGCheck_Owner',
                    'Request DT': 'DGCheck_StartDate',
                    'PlanIn DT': 'DGCheck_StartDate',
                    'Planned DT': 'DGCheck_EndDate',
                    'Completed DT': None,
                    'Comment': 'Label',
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': f'${hr_perday}',
                    'Priority': '$3',
                    'LogType': '$系統-開發-DGC',
                    'ReqTeam': '$PG',
                    'ownModule': None,
                    'logKey': None,
                    'reportID': 'Task#',
                    'isRTC': '$False',
                    'rptName': None,
                    'defaultTeam': '$PG',
                    'Remark': '$N/A',
                }],
                stage_names = [
                    {'short_name': 'BA', 'long_name': 'BA'},
                    {'short_name': 'DG', 'long_name': 'DG'},
                    {'short_name': 'DM', 'long_name': 'DM'},
                    {'short_name': 'ETL', 'long_name': 'ETL'},
                    {'short_name': 'RPT', 'long_name': 'RPT'},
                    {'short_name': 'FT', 'long_name': 'FuncTest'},
                    {'short_name': 'DGC', 'long_name': 'DGCheck'},
                    # 'DG', 'TC', 'DM', 'FT', 'WT'
                ],
                map_name={
                    'Alex YH Chen': 'Alex',
                    'Anna Yang': 'Anna',
                    'Brian Hung': 'Brian',
                    'Cindy Cheng': 'Cindy',
                    'Cynthia Lin': 'CynthiaLin',
                    'Dennis Huang': 'Dennis',
                    'Effie Lin': 'Effie',
                    'Ellen Sun': 'EllenSun',
                    'Jane Liu': 'Jane',
                    'Johnny Kao': 'Johnny',
                    'Redmine Admin': 'Redmine',
                    'Sean Chiu': 'Sean',
                    'Stella Tseng': 'Stella',
                    'Sunny Chnag': 'Sunny',
                    'Joseph Wong': 'Joseph',
                    'ho2002': 'Aiden',
                    'benjaminchenibm': 'Benjamin',
                    'Irene.Tsai': 'Irene',
                    'ickw76': 'Issac',
                    'scliang123': 'Janus',
                    'rickyho': 'Ricky',
                    'soniayml': 'Sonia',
                    'flyingsophiee': 'Sophie',
                    'CassieLee': 'Cassie',
                    'linwj130013': 'Ivy',
                    'dcnlin': 'Deacon',
                    'marrinakong': 'Marrina',
                    'kuantsung.chen': 'KT',
                    'Jesse Wei': 'Jesse',
                    'gracechien2': 'Grace',
                    'Johnson Feng': 'JohnsonFeng',
                    'Felix Kuan': 'Felix',
                    'Jamie lin': 'Jamie',
                    'Ricky Ho': 'Ricky',
                    'Valen Chang': 'Valen',
                    'Viola Lin': 'Viola',
                    'Viola2 Lin': 'Viola',
                    '-': 'PMO',
                },
                map_state={
                    'Assigned': 'Process',
                    # 'Completed': 'Completed',
                    'Not started': 'Process',
                    'Open': 'Process',
                    'Opened': 'Process',
                    # 'Process': 'Process',
                    'Rejected': 'Cancelled',
                    'Rejected Closed': 'Cancelled',
                    'Resolved': 'Completed',
                    'Submitted': 'Process',
                    'Verify Closed': 'Completed',
                },
                map_priority={
                    'Critical': '5',
                    'High': '4',
                    'Medium': '3',
                    'Low': '2',
                },
                category_map = {
                    'PRODUCT': 'PROD',
                },
                map_log_type=dict(
                ),
                module_map = {
                    'PRODUCT': 'PROD',
                    'PROPOSAL': 'REQ',
                    'CAMPAIGN': 'PROJ',
                    'REPORT': 'MEM',
                    'LIBRARY': 'LIB',
                    'WORKFLOW': 'ADM',
                    'COMMON': 'ADM',
                    '': 'ADM',
                },
                
            
            ),
            'sharepoint':dict(
                grant_type= "client_credentials",
                resource = "00000003-0000-0ff1-ce00-000000000000/inventeccorp.sharepoint.com@2ae41f0c-acca-40f1-9c63-49475ff38512",
                client_id = " f0832da5-e6d1-40e4-918d-35ff8e833369@2ae41f0c-acca-40f1-9c63-49475ff38512",
                client_secret = " L7gSZcd3QBcFbMxIVjVSxoeCGyMDDnswjfbboPBr/ME=",
                prj_id='18454432',
                comment_addr = "https://inventeccorp.sharepoint.com/sites/msteams_e8e153_245270/_api/Web/lists/GetByTitle(\'Issue Tracker\')/items({0})/GetComments",
                tokenURL = "https://accounts.accesscontrol.windows.net/2ae41f0c-acca-40f1-9c63-49475ff38512/tokens/OAuth/2",
                addr = "https://inventeccorp.sharepoint.com/sites/msteams_e8e153_245270/_api/Web/lists/GetByTitle(\'Issue Tracker\')/RenderListDataAsStream",
                prj_dir='C:/PROJ_DIR/1_PM/1.0_Backlog/',
                keycode='SP',
                tgt_file='IEC-SP.xlsx',
                row_per_page=100,
                cmt_mode = False,
                map_columns={
                    'Category': '$SP',
                    'Story': 'Title',
                    'Solution/Confirmation': 'Description',
                    'Status': 'Status',
                    'Owner': "AssignTo.title",
                    'Stakeholder': "IssueLoggedBy.title",
                    'Request DT': 'Created',
                    'PlanIn DT': 'PlanInDate',
                    'Planned DT': 'DueDate',
                    'Completed DT': 'DueDate',
                    'Comment': None,
                    'GTD': None,
                    'Remain HR': f'${hr_perday}',
                    'Ideal HR': f'${hr_perday}',
                    'Story Point': '$1',
                    'Priority': 'Priority',
                    'LogType': 'LogType',
                    'ReqTeam': '$DG',
                    'ownModule': None,
                    'logKey': 'ID',
                    'reportID': None,
                    'isRTC': None,
                    'rptName': None,
                    'defaultTeam': '$DG',
                    'Remark': '$N/A',
                },
                map_name={
                    'Allen WL Syu': 'Allen Syu',
                    'Jen.Austin 任曉珍 IEC1': 'Jen.Austin',
                    'Winnie WY Lo': 'Winnie Lo',
                    'Belle YJ Lin': 'Belle Lin',
                    'Wei Jesse': 'Jesse Wei',         
                    'Bucky YH Lee': 'Bucky Lee',
                    'Linda An': 'Linda An',           
                    'Hank Chen': 'Hank Chen',
                    'Lien CL Ku': 'Lien Ku',
                    'York HE Kuo': 'York Kuo',
                    'Irene Lin': 'Irene Lin',
                    'MJ H Hsieh':'MJ Hsieh',
                    'Jenny Chen':'Jenny Chen',
                    'Cathy Lin': 'Cathy Lin',
                    'Flora Po':'Flora Po',
                    'Jacob Lee':'Jacob Lee',
                    'Susan Huang':'Susan Huang',
                    'kyle.wei':'Kyle Wei',
                    'An Ting Teng':'Anting Teng',
                    'Pin YP Yu':'Pin Yu',
                    'johnnyym':'Johnny Kao',
                    'Foster.Yo':'Foster Yo',
                    'Tsai.Jack 蔡枝安 TAO':'Jack Tsai',
                    'Yeh.LC 葉力誠 IEC1':'Sam Yeh',
                    'Chen.Wei-Chao 陳維超 IEC1' : 'Weichao Chen',
                    'Li.Lino 李瑞進 TAO':'Lino Lee',
                    'Chen.Maxine 陳芷伶 IEC1':'Maxine Chen',
                    'Li.Joseph 李進源 TAO':'Joseph Li',
                    'Wang.Ian 王一安 TAO':'Ian Wang',
                    'Huang.Hendry 黃英哲 TAO':'Hendry Huang',
                    'Chao.Daphne 趙彩秀 TAO':'Daphne Chao',
                    'Ju.Vivian 朱惠琴 TAO':'Vivian Ju',
                    'Huang.LM 黃立孟 TAO':'LM Huang',
                    'Peng.KY 彭光裕 TAO':'KY Peng',
                    'Huang.Patrick 黃丕佑 TAO': 'Patrick Huang',
                    'Lee.AlexML 李明倫 TAO':'Alex Lee',
                    'Liao.Lily 廖笠婷 TAO':'Lily Liao',
                    'Feng.Nicole 馮家芳 TAO':'Nicole Feng',
                    'Lin.Peter-Tao 林倍揚 TAO':'Peter Lin',
                    'Yen.Jerry 閻承隆 TAO':'Jerry Yen',
                    'Fan.Gang 范剛 ITC':'Fan.Gang',
                    'Lin.JanetT.Y 林姿佑 TAO':'Janet Lin',
                    'Lee.JennyHC 李雪菁 TAO':'Jenny Lee',
                    'Lin.Una 林榆虹 TAO':'Una Lin',
                    'Yang.Milly 楊千慧 TAO':'Milly Yang',
                    'Yu.FloraHJ 游惠茹 TAO':'Flora Yu',
                    'Wang.JoyceCY 汪靜怡 TAO':'Joyce Wang',
                    'Yang.Abe 楊長良 TAO':'Abe Yang',
                    'Lin.Jacky 林嘉麒 TAO':'Jacky Lin',
                    'Yu.JamesKH 俞國華 TAO':'James Yu',
                    'Yang.Brian 楊士興 TAO' :'Brian Yang',
                    'Lin.Lewie 林鈺淵 TAO':'Lin.Lewie',
                    'Tu.Joanne 塗蕓緁 TAO':'Joanne Tu',
                    'Chen.AlbertYC 陳彥呈 IEC1':'Albert Chen',
                    'Chang.Zuro 張明淇 IEC1':'Zuro Chang',
                    'Huang.Chen-I 黃侲艗 IEC1':'Chen-I Huang',
                    'Ni.Roger 倪崇勝 TAO':'Roger Ni',
                    'Chu.Kelly 朱容瑩 TAO':'Kelly Chu',
                    'Tsou.Kelly 鄒莉君 TAO':'Kelly Tsou',
                    'Ma.Vivian 馬如瑩 IEC1':'Vivian Ma',             
                    'Yeh.Peggy 葉珮帆 TAO':'Peggy Yeh', 
                    'Hsieh.Nydia 謝旻文 TAO': 'Nydia Hsieh',
                    'Lin.Irene 林幸灴 TAO': 'Irene Lin',
                    'Wu.Gary 吳卓叡 IEC1': 'Gary Wu',
                    'Lee.Miles 李建中 TAO': 'Miles Lee',
                    'Liang.Sharon 梁雪雲 TAO':'Sharon Liang',
                    'Huang.Joe-Win 黃禎文 TAO': 'Joe-win Huang',
                    'Wang.Carol 王麗卿 TAO':'Carol Wang',
                    'Hsieh.FrankSU 謝祥昱 TAO':'Frank Hsieh',
                    'Tsai.Shang-Ju 蔡尚儒 IEC1':'Shang Ju Tsai',
                    'Tseng.Becky 曾于珊 TAO':'Becky Tseng',
                    'Hsieh.PeterC.W 謝志偉 IEC1':'Peter Hsieh',
                    'Chen.CH 陳琦璇 TAO':'CH Chen',
                    'Chen.Yun-Hong 陳蘊弘 ITC':'Yun-Hong Chen',
                    'Wu.Jimmy 巫進益 TAO':'Jimmy Wu',
                    'Wang.Jason 王建勝 TAO':'Jason Wang',
                    'Liu.SJ 劉芊嶠 TAO':'SJ Liu',
                    'Chung.PH 鍾沛寰 IEC1':'Chung.PH',
                    'Kung.JH 龔志鴻 TAO':'JH Kung',
                    'Tseng.Sammy 曾獻明 TAO':'Sammy Tseng',
                    'Chen.JoyceFW 陳斐文 TAO':'Joyce Chen',
                    'Wang.Zong-Lan 王宗蘭 ITC':'Wang.Zong-Lan',
                    'Wei.Stephen 魏智斌 IEC1':'Stephen Wei',
                    'Chiu.Lillian 邱宜姿 TAO':'Lillian Chiu',
                    'Cho.Wiley 卓儀香 IEC1':'Wiley Cho',
                    'Wu.Bryan 吳海峰 IEC1':'Bryan Wu',
                    'Huang.DuncanYD 黃玉德 TAO':'Duncan Huang',
                    'Huang.EvaYF 黃韻芳 TAO':'Eva Huang',
                    'Lin.Aero 林慶芳 IEC1':'Aero Lin',
                    'Chen.JennyYT 陳怡婷':'Jenny Chen',
                    'Wei.Jesse 魏鴻雄 TAO':'Jesse Wei',
                    'Lee.Seven 李思穎 IEC1':'Seven Lee',
                    'Huang.Vivien 黃筱汶 TAO':'Vivien Huang',
                    'Li.Pear 黎思函 TAO':'Pear Li',
                    'Liou.Alan 劉明鑫 TAO':'Alan Liou',
                    'Huang.Ema 黃嘉玫 TAO':'Ema Huang',
                    'Chen.SB 陳秀碧 TAO':'SB Chen',
                    'Hsu.Andy 許皓嘉 TAO':'Andy Hsu',
                    'Wang.Lan-Xiang 王蘭香 ITC':'Lang Xiang Wang',
                    'Lee.Bucky 李彥璇 TAO':'Bucky Lee',
                    'Li.Lily 李麗 IES': 'Lily Li',
                    'Huang.Susan 黃舒瑜 TAO':'Susan Huang',
                    'Li.Lily 李麗 IES':'Lily Li',
                    'Lee.Wen 李友文 TAO':'Wen Lee',
                    'Huang.JasonJW 黃建豐 TAO':'Jason Huang',
                    'Wei.Xiao-qin 韋小琴 IES':'Xiao-qin Wei',
                    'Shen.Sherry 沈姵如 TAO':'Sherry Shen',
                    'Huang.SamXS 黃顯順 IES':'SamXS Huang',
                    'Gong.Debby 龔子麗 TAO':'Debby Gong',
                    'Jian.Jason 簡嘉興 TAO':'Jason Jian',
                    'Liu.Angel 劉美芳 TAO':'Angel Liu',
                    'Ku.Andy 顧宗弘 TAO':'Andy Ku',
                    'Tsai.Eirik 蔡宜呈 TAO ':'Eirik Tsai',
                    'Liang.Jason 梁可翰 IES':'Jason Liang',
                    'Wu.Alice 吳欣宜 IEC1':'Alice Wu',
                    'Yang.Jasmine 楊思嘉 TAO':'Jasmine Yang',
                    'Chao.May 趙美晏 TAO':'May Chao',
                    'Huang.Kevin 黃偉榮 TAO':'Kevin Huang',
                    'Kung.Gary 孔見超 IES':'Gary Kung',
                    'Liu.Hui 劉會 IES':'Liu.Hui 劉會',
                    'Chen.Justen 陳俞帆 IES':'Justen Chen',
                    'Cheng.Roger 鄭俊豪 TAO':'Roger Cheng',
                    'Jenny YT Chen':'Jenny Chen',
                    'Chen.Leanne 陳俐安 TAO':'Leanne Chen',
                    'Shen.Marco 沈棟棟 IES':'Marco Shen',
                    'Xu.Hongxia 徐紅霞 IES':'Hongxia Xu',
                    'Lee.Belle 李靜雯 TAO':'Belle Lee',
                    'Yu.Rebecca 游婷瑄 TAO':'Rebecca Yu',
                    'Kao.Vinla 高詠善 TAO':'Vinla Kao',
                    'Lin.Migrant 林瑞益 IEC1':'Lin.Migrant',
                    'Lin.AlvinC.H 林政宏 ICC':'Lin.AlvinC.H',
                    'Chen.Len 陳建銘 ICC':'Chen.Len',                
                    'Chen.Len 陳建銘 IEC1':'Chen.Len',                
                    'Su.May 蘇慧中 IEC1':'Su.May',                
                    'Huang.Karen 黃曉苓 IEC1':'Huang.Karen',                
                    'Chu.May 儲德梅 IEC1':'Chu.May',        
                    'Qian.Jenny 錢珍 ICC':'Qian.Jenny',        
                    'Hsueh.Daniel 薛喨 IEC1':'Hsueh.Daniel',        
                    'Liao.Vic 廖奕醒 IEC1':'Liao.Vic',        
                    'Chiu.Winnie 邱雯鈴 IEC1':'Winnie Chiu',        
                    'Tan.Tansy 譚成淑 ICC':'Tan.Tansy',        
                    'Hung.Cathy 洪秀瑜 IEC1':'Hung.Cathy', 
                    'Lee.VincentKS 李坤樹 IEC1':'Lee.VincentKS',       
                    'Yang.KimiYP 楊雅萍 IEC1':'Yang.KimiYP',       
                    'Chang.AndyCY 張哲瑜 IEC1':'Chang.AndyCY',
                    'Lin.Vic 林凱翊 IEC1':'Lin.Vic',
                    'Wen.Vivian 溫麗華 IEC1':'Wen.Vivian',
                    'Chen.Ivy 陳素貞 IEC1':'Chen.Ivy',
                    'Jhan.Stan 詹世毓 IEC1':'Jhan.Stan',
                    '-': 'TBD',
                },
                map_state={
                    'Completed': 'Completed',
                    'In progress': 'Process',
                    'New':'Process',
                    '-': 'Process',
                },
                map_priority={
                    'Critical': '5',
                    'High': '4',
                    'Normal': '3',
                    'Low': '2',
                }

            
            
        )
        }
    ),
    similarity=dict(       
        prj_dir = '/Users/$USER/Documents/proj_dir/20_DG/2000_Standard/',
        in_file = 'P20_Elaboration/2000_Standard/IECP2-DG-MTD-v2.0c.xlsm',
        out_file = 'P20_Elaboration/2000_Standard/IECP2-DG-MTD-Similarity.xlsx'
        
                
    ),
    matching=dict(       
        in_file = 'DG_IEC_STD_V10_MtdMatch.csv',
        PURVIEW_NAME = 'Digital-Center-Purview-Dev',
        AZURE_CLIENT_ID = 'b706f858-6367-4550-9df6-769c8ac269c9',
        AZURE_TENANT_ID = '2ae41f0c-acca-40f1-9c63-49475ff38512',
        AZURE_CLIENT_SECRET = 'Afi7Q~_IlU5yFSFUj5COq189e1o4n06pyVxJO'
                      
    ), 
)
