@startuml

skinparam componentStyle uml2

package "'CustomerFrontend' Aggregate" <<Rectangle>> {
	class CustomerAddressChange <<(A,#fffab8) Aggregate Root>> {
		UserAccount issuer
		Address changedAddress
	}
}
package "'Acounts' Aggregate" <<Rectangle>> {
	class UserAccount <<(A,#fffab8) Aggregate Root>> {
		String username
		Customer accountCustomer
	}
}
CustomerAddressChange --> UserAccount : issuer
legend left
  This bounded context implements the subdomain 'CustomerManagementDomain'.
end legend


@enduml
