@startuml

skinparam componentStyle uml2

package "'CustomerFrontend' Aggregate" <<Rectangle>> {
	class CustomerAddressChange <<(A,#fffab8) Aggregate Root>> {
		UserAccount issuer
		Address changedAddress
	}
}


@enduml
